import { burgerElements } from './burger-element';
import { initialState } from './burger-element';

import {
    ADD_BURGER_ELEMENT,
    ADD_BUN_ELEMENT,
    SORT_BURGER_ELEMENT,
    DEL_BURGER_ELEMENT,
} from '../actions/burger-element';


describe("burger elements reduser", () => {

    it("initial state", () => {
        expect(burgerElements(undefined, {})).toEqual(initialState);
    })


    it("add burger element", () => {
        expect(burgerElements(initialState, {
            type: ADD_BURGER_ELEMENT,
            burgerElement: {
                _id: "643d69a5c3f7b9001cfa0943",
                name: "Соус фирменный Space Sauce",
                type: "sauce",
                proteins: 50,
                fat: 22,
                carbohydrates: 11,
                calories: 14,
                price: 80,
                image: "https://code.s3.yandex.net/react/code/sauce-04.png",
                image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
                image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
                __v: 0,
            }
        })).toEqual({
            bun: {
                calories: 0,
                carbohydrates: 0,
                fat: 0,
                image: '',
                image_large: '',
                image_mobile: '',
                name: '',
                price: 0,
                proteins: 0,
                type: '',
                __v: 0,
                _id: 'string',
            },
            burgerElement: [{
                _id: "643d69a5c3f7b9001cfa0943",
                name: "Соус фирменный Space Sauce",
                type: "sauce",
                proteins: 50,
                fat: 22,
                carbohydrates: 11,
                calories: 14,
                price: 80,
                image: "https://code.s3.yandex.net/react/code/sauce-04.png",
                image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
                image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
                __v: 0,
            }],
        });
    })

    it("add bun element", () => {
        expect(burgerElements(initialState, {
            type: ADD_BUN_ELEMENT,
            bun: {
                _id: "643d69a5c3f7b9001cfa093d",
                name: "Флюоресцентная булка R2-D3",
                type: "bun",
                proteins: 44,
                fat: 26,
                carbohydrates: 85,
                calories: 643,
                price: 988,
                image: "https://code.s3.yandex.net/react/code/bun-01.png",
                image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
                image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
                __v: 0
            }
        })).toEqual({
            bun: {
                _id: "643d69a5c3f7b9001cfa093d",
                name: "Флюоресцентная булка R2-D3",
                type: "bun",
                proteins: 44,
                fat: 26,
                carbohydrates: 85,
                calories: 643,
                price: 988,
                image: "https://code.s3.yandex.net/react/code/bun-01.png",
                image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
                image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
                __v: 0
            },
            burgerElement: [],
        });
    })






    it("sort burger element", () => {
        expect(burgerElements({
            bun: {
                _id: "643d69a5c3f7b9001cfa093d",
                name: "Флюоресцентная булка R2-D3",
                type: "bun",
                proteins: 44,
                fat: 26,
                carbohydrates: 85,
                calories: 643,
                price: 988,
                image: "https://code.s3.yandex.net/react/code/bun-01.png",
                image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
                image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
                __v: 0,
            },
            burgerElement: [
                {
                    _id: "643d69a5c3f7b9001cfa0943",
                    name: "Соус фирменный Space Sauce",
                    type: "sauce",
                    proteins: 50,
                    fat: 22,
                    carbohydrates: 11,
                    calories: 14,
                    price: 80,
                    image: "https://code.s3.yandex.net/react/code/sauce-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
                    __v: 0,
                    namber: 6259,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0940",
                    name: "Говяжий метеорит (отбивная)",
                    type: "main",
                    proteins: 800,
                    fat: 800,
                    carbohydrates: 300,
                    calories: 2674,
                    price: 3000,
                    image: "https://code.s3.yandex.net/react/code/meat-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
                    __v: 0,
                    namber: 3084,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0948",
                    name: "Кристаллы марсианских альфа-сахаридов",
                    type: "main",
                    proteins: 234,
                    fat: 432,
                    carbohydrates: 111,
                    calories: 189,
                    price: 762,
                    image: "https://code.s3.yandex.net/react/code/core.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/core-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/core-large.png",
                    __v: 0,
                    namber: 2840,
                },
                {
                    _id: "643d69a5c3f7b9001cfa094a",
                    name: "Сыр с астероидной плесенью",
                    type: "main",
                    proteins: 84,
                    fat: 48,
                    carbohydrates: 420,
                    calories: 3377,
                    price: 4142,
                    image: "https://code.s3.yandex.net/react/code/cheese.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/cheese-large.png",
                    __v: 0,
                    namber: 5526,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0940",
                    name: "Говяжий метеорит (отбивная)",
                    type: "main",
                    proteins: 800,
                    fat: 800,
                    carbohydrates: 300,
                    calories: 2674,
                    price: 3000,
                    image: "https://code.s3.yandex.net/react/code/meat-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
                    __v: 0,
                    namber: 2477,
                },
            ],
        }, {
            type: SORT_BURGER_ELEMENT,
            newCards: [
                {
                    _id: "643d69a5c3f7b9001cfa0943",
                    name: "Соус фирменный Space Sauce",
                    type: "sauce",
                    proteins: 50,
                    fat: 22,
                    carbohydrates: 11,
                    calories: 14,
                    price: 80,
                    image: "https://code.s3.yandex.net/react/code/sauce-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
                    __v: 0,
                    namber: 6259,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0940",
                    name: "Говяжий метеорит (отбивная)",
                    type: "main",
                    proteins: 800,
                    fat: 800,
                    carbohydrates: 300,
                    calories: 2674,
                    price: 3000,
                    image: "https://code.s3.yandex.net/react/code/meat-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
                    __v: 0,
                    namber: 3084,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0940",
                    name: "Говяжий метеорит (отбивная)",
                    type: "main",
                    proteins: 800,
                    fat: 800,
                    carbohydrates: 300,
                    calories: 2674,
                    price: 3000,
                    image: "https://code.s3.yandex.net/react/code/meat-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
                    __v: 0,
                    namber: 2477,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0948",
                    name: "Кристаллы марсианских альфа-сахаридов",
                    type: "main",
                    proteins: 234,
                    fat: 432,
                    carbohydrates: 111,
                    calories: 189,
                    price: 762,
                    image: "https://code.s3.yandex.net/react/code/core.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/core-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/core-large.png",
                    __v: 0,
                    namber: 2840,
                },
                {
                    _id: "643d69a5c3f7b9001cfa094a",
                    name: "Сыр с астероидной плесенью",
                    type: "main",
                    proteins: 84,
                    fat: 48,
                    carbohydrates: 420,
                    calories: 3377,
                    price: 4142,
                    image: "https://code.s3.yandex.net/react/code/cheese.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/cheese-large.png",
                    __v: 0,
                    namber: 5526,
                },

            ]
        })).toEqual({
            bun: {
                _id: "643d69a5c3f7b9001cfa093d",
                name: "Флюоресцентная булка R2-D3",
                type: "bun",
                proteins: 44,
                fat: 26,
                carbohydrates: 85,
                calories: 643,
                price: 988,
                image: "https://code.s3.yandex.net/react/code/bun-01.png",
                image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
                image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
                __v: 0,
            },
            burgerElement: [
                {
                    _id: "643d69a5c3f7b9001cfa0943",
                    name: "Соус фирменный Space Sauce",
                    type: "sauce",
                    proteins: 50,
                    fat: 22,
                    carbohydrates: 11,
                    calories: 14,
                    price: 80,
                    image: "https://code.s3.yandex.net/react/code/sauce-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
                    __v: 0,
                    namber: 6259,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0940",
                    name: "Говяжий метеорит (отбивная)",
                    type: "main",
                    proteins: 800,
                    fat: 800,
                    carbohydrates: 300,
                    calories: 2674,
                    price: 3000,
                    image: "https://code.s3.yandex.net/react/code/meat-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
                    __v: 0,
                    namber: 3084,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0940",
                    name: "Говяжий метеорит (отбивная)",
                    type: "main",
                    proteins: 800,
                    fat: 800,
                    carbohydrates: 300,
                    calories: 2674,
                    price: 3000,
                    image: "https://code.s3.yandex.net/react/code/meat-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
                    __v: 0,
                    namber: 2477,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0948",
                    name: "Кристаллы марсианских альфа-сахаридов",
                    type: "main",
                    proteins: 234,
                    fat: 432,
                    carbohydrates: 111,
                    calories: 189,
                    price: 762,
                    image: "https://code.s3.yandex.net/react/code/core.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/core-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/core-large.png",
                    __v: 0,
                    namber: 2840,
                },
                {
                    _id: "643d69a5c3f7b9001cfa094a",
                    name: "Сыр с астероидной плесенью",
                    type: "main",
                    proteins: 84,
                    fat: 48,
                    carbohydrates: 420,
                    calories: 3377,
                    price: 4142,
                    image: "https://code.s3.yandex.net/react/code/cheese.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/cheese-large.png",
                    __v: 0,
                    namber: 5526,
                },

            ],
        });
    })





    it("del burger element", () => {
        expect(burgerElements({
            bun: {
                _id: "643d69a5c3f7b9001cfa093d",
                name: "Флюоресцентная булка R2-D3",
                type: "bun",
                proteins: 44,
                fat: 26,
                carbohydrates: 85,
                calories: 643,
                price: 988,
                image: "https://code.s3.yandex.net/react/code/bun-01.png",
                image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
                image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
                __v: 0,
            },
            burgerElement: [
                {
                    _id: "643d69a5c3f7b9001cfa0943",
                    name: "Соус фирменный Space Sauce",
                    type: "sauce",
                    proteins: 50,
                    fat: 22,
                    carbohydrates: 11,
                    calories: 14,
                    price: 80,
                    image: "https://code.s3.yandex.net/react/code/sauce-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
                    __v: 0,
                    namber: 6259,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0940",
                    name: "Говяжий метеорит (отбивная)",
                    type: "main",
                    proteins: 800,
                    fat: 800,
                    carbohydrates: 300,
                    calories: 2674,
                    price: 3000,
                    image: "https://code.s3.yandex.net/react/code/meat-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
                    __v: 0,
                    namber: 3084,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0948",
                    name: "Кристаллы марсианских альфа-сахаридов",
                    type: "main",
                    proteins: 234,
                    fat: 432,
                    carbohydrates: 111,
                    calories: 189,
                    price: 762,
                    image: "https://code.s3.yandex.net/react/code/core.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/core-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/core-large.png",
                    __v: 0,
                    namber: 2840,
                },
                {
                    _id: "643d69a5c3f7b9001cfa094a",
                    name: "Сыр с астероидной плесенью",
                    type: "main",
                    proteins: 84,
                    fat: 48,
                    carbohydrates: 420,
                    calories: 3377,
                    price: 4142,
                    image: "https://code.s3.yandex.net/react/code/cheese.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/cheese-large.png",
                    __v: 0,
                    namber: 5526,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0940",
                    name: "Говяжий метеорит (отбивная)",
                    type: "main",
                    proteins: 800,
                    fat: 800,
                    carbohydrates: 300,
                    calories: 2674,
                    price: 3000,
                    image: "https://code.s3.yandex.net/react/code/meat-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
                    __v: 0,
                    namber: 2477,
                },
            ],
        }, {
            type: DEL_BURGER_ELEMENT,
            id: 2477,
        })).toEqual({
            bun: {
                _id: "643d69a5c3f7b9001cfa093d",
                name: "Флюоресцентная булка R2-D3",
                type: "bun",
                proteins: 44,
                fat: 26,
                carbohydrates: 85,
                calories: 643,
                price: 988,
                image: "https://code.s3.yandex.net/react/code/bun-01.png",
                image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
                image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
                __v: 0,
            },
            burgerElement: [
                {
                    _id: "643d69a5c3f7b9001cfa0943",
                    name: "Соус фирменный Space Sauce",
                    type: "sauce",
                    proteins: 50,
                    fat: 22,
                    carbohydrates: 11,
                    calories: 14,
                    price: 80,
                    image: "https://code.s3.yandex.net/react/code/sauce-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
                    __v: 0,
                    namber: 6259,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0940",
                    name: "Говяжий метеорит (отбивная)",
                    type: "main",
                    proteins: 800,
                    fat: 800,
                    carbohydrates: 300,
                    calories: 2674,
                    price: 3000,
                    image: "https://code.s3.yandex.net/react/code/meat-04.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/meat-04-large.png",
                    __v: 0,
                    namber: 3084,
                },
                {
                    _id: "643d69a5c3f7b9001cfa0948",
                    name: "Кристаллы марсианских альфа-сахаридов",
                    type: "main",
                    proteins: 234,
                    fat: 432,
                    carbohydrates: 111,
                    calories: 189,
                    price: 762,
                    image: "https://code.s3.yandex.net/react/code/core.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/core-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/core-large.png",
                    __v: 0,
                    namber: 2840,
                },
                {
                    _id: "643d69a5c3f7b9001cfa094a",
                    name: "Сыр с астероидной плесенью",
                    type: "main",
                    proteins: 84,
                    fat: 48,
                    carbohydrates: 420,
                    calories: 3377,
                    price: 4142,
                    image: "https://code.s3.yandex.net/react/code/cheese.png",
                    image_mobile: "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                    image_large: "https://code.s3.yandex.net/react/code/cheese-large.png",
                    __v: 0,
                    namber: 5526,
                },

            ],
        });
    })

})
