export const ADD_BURGER_ELEMENT = 'ADD_BURGER_ELEMENT';
export const DEL_BURGER_ELEMENT = 'DEL_BURGER_ELEMENT';
export const ADD_BUN_ELEMENT = 'ADD_BUN_ELEMENT';
export const SORT_BURGER_ELEMENT = 'SORT_BURGER_ELEMENT';